version: '3.8'
services:
  mysql-db:   
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: roottoor   
      MYSQL_DATABASE: bioaqua         
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  bioaqua-api:
    image:  bioaqua-api:latest
    container_name: bioaqua-api
    volumes:
      - /opt/firebase/firebase-adminsdk.json:/app/secrets/firebase-adminsdk.json
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/bioaqua?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: roottoor
    depends_on:
      - mysql-db

volumes:
  mysql_data:
