spring:
  application:
    name: bioaqua
  datasource:
    url: jdbc:mysql://mysql-db:3306/bioaqua?createDatabaseIfNotExist=true
    username: root
    password: roottoor
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.zoho.com
    port: 465
    username: abderrahmen.talby@thexbyte.com.tn
    password: 4S0JQSqnU0zC
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport.protocol: smtps
        debug: true
  servlet:
    context-path: /api
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
  packages-to-scan: com.thexbyte.bioaqua.controllers
